# Site
name: 'Tech Writing Brasil'
description: 'Comunidade de tech writers do Brasil'
logo: '/assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: ''
email: 'techwritingbrasil@gmail.com'
mailchimp-list: 'https://techwriting.us10.list-manage.com/subscribe/post?u=fb38eb12d33cbde20166321fe&amp;id=e0b6019ef1'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    brenoBarreto:
      name:           Breno Barreto
      linkedIn:       https://techscribe.substack.com/welcome
      avatar:         assets/images/brenoBarreto.jpg
      bio:            "Lead Technical Writer @ VTEX | Co-host do podcast The Manuscript | Autor da newsleter Tech Scribe"
      email:          breno.oliveira@gmail.com
      twitter:        https://twitter.com/scribe_tech
      medium:         https://medium.com/@breno.barreto

    julianaMeyer:
      name:           Juliana Meyer
      linkedIn:       https://www.linkedin.com/in/oijulianameyer
      avatar:         assets/images/julianaMeyer.jpg
      bio:            "Technical Writer @ VTEX | Co-host do podcast The Manuscript"
      email:          
      twitter:        
      medium:         https://medium.com/@jumeyermattosarruda

          
    marianaMoreira:
      name:           Mariana Moreira
      linkedIn:       https://www.linkedin.com/in/marianacpmoreira
      avatar:         assets/images/marianaMoreira.png
      bio:            "Technical Writer @ Zup Innovation"
      email:          
      twitter:        https://twitter.com/mdcpmoreira
      medium:         https://medium.com/@marianacpmoreira

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]